logging:
  level:
    root: info
  pattern:
    console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    # Connection properties of Data Source A
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/foos?createDatabaseIfNotExist=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    # Connection properties of Data Source B
    psql:
      jdbc-url: jdbc:postgresql://localhost:5432/bars
      driver-class-name: org.postgresql.Driver
      username: andreystoev
      password: password
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

# sudo pkill -u postgres
